### PR TITLE
ModelBase, Take II

### PR DESCRIPTION
**Pull request by andenixa**
Apologies the before PR. That was kind of silly of me.

Here is get_model_name redone properly; tested with Python 3.6 x64

I like the repo thus I wanted to do the commit (and it would also help me to add my models without thinking of naming these).

Actually I could have re-factored the whole thing, but you might not like it. Though offer still stands.

### CODE REVIEW

**Comment by iperov** [comment]
test also on 3.5 plz

**Comment by iperov** [comment]
> Actually I could have re-factored the whole thing

why ? I dont like redundant refactorings

**Comment by andenixa** [comment]
@iperov 
There is always a way to make code more appealing to simpler audience. But as I said you probably would not like it.
I could have used more decorators (closures), i.e. for events, such as "@onPreview".
I am not saying its in improvement, but probably easier to understand for newcomers.

**Comment by iperov** [comment]
I am newcomer, I dont know decorators.

**Comment by iperov** [comment]
newcomers will spend time to study decorators first?

**Comment by iperov** [comment]
```
@onPreview(some arguments)
def myPreview(samples):
    some stuff here
```
and how modelbase will call overloaded func to get preview ?

**Pull request merged**
